version: '3'

services:
  events-consumer-service:
      image: events-consumer-service:latest
      container_name: events-consumer-service
      build:
        context: events_consumer_service
      ports:
        - "8001:5000"
      depends_on:
        - reporting_scylla_db
      environment:
        KAFKA_TOPICS: User,Link,LinkMetric
        KAFKA_ADVERTISED_HOST_NAME: kafka
        KAFKA_ADVERTISED_PORT: 19092

  reporting_scylla_db:
    container_name: reporting-scylla-db
    image: scylladb/scylla:4.5.0
    restart: always
    command: --seeds=reporting_scylla_db --smp 1 --memory 1054M --overprovisioned 1 --api-address 0.0.0.0
    ports:
      - "9042:9042"
    volumes:
      - ./data/scylla_db:/data/scylla

  es01:
    image: elasticsearch:7.2.0
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - xpack.security.enabled=false
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTIONS=-Xms512m -Xmx512m -XX:-UseConcMarkSweepGC
                                        -XX:-UseCMSInitiatingOccupancyOnly
                                        -XX:+UseG1GC
                                        -XX:InitiatingHeapOccupancyPercent=75"
      - MEM_LIMIT=262144
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch:/data/elasticsearch
    ports:
      - 9200:9200
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch:/data/elasticsearch

  kibana:
      container_name: kb-container
      image: docker.elastic.co/kibana/kibana:7.2.0
      environment:
        - ELASTICSEARCH_HOSTS=http://es01:9200
      depends_on:
        - es01
      ports:
        - 5601:5601
