apiVersion: v1
kind: Service
metadata:
  name: events-consumer-service
spec:
  selector:
    component: events-consumer-deployment
  ports:
    - port: 8001
      protocol: TCP
      targetPort: 8001
  type: ClusterIP