kind: Deployment
apiVersion: apps/v1
metadata:
  name: zookeeper-deployment
  labels:
    component: zookeeper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: zookeeper-deployment
  template:
    metadata:
      labels:
        component: zookeeper-deployment
    spec:
      containers:
        - name: zoo1
          image: zookeeper:3.4.9
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_ID
              value: "1"
            - name: ZOOKEEPER_SERVER_1
              value: "2181"
