apiVersion: v1
kind: Service
metadata:
  name: zoo1
  labels:
    component: zookeeper-deployment
spec:
  ports:
    - name: client
      port: 2181
      protocol: TCP
    - name: follower
      port: 2888
      protocol: TCP
    - name: leader
      port: 3888
      protocol: TCP
  selector:
    component: zookeeper-deployment