apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  labels:
    component: kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: kafka-deployment
  template:
    metadata:
      labels:
        component: kafka-deployment
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:6.1.1
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: "kafka-service:9092"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zoo1-service:2181
            - name: KAFKA_BROKER_ID
              value: "kafka-deployment"
            - name: KAFKA_CREATE_TOPICS
              value: admintome-test:1:1
            - name: KAFKA_JMX_PORT
              value: "9999"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-service:9092"
          volumeMounts:
            - name: kafka-volume-container
              mountPath: /data/kafka
      volumes:
        - name: kafka-volume-container
          persistentVolumeClaim:
            claimName: kafka-volume



