apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  labels:
    component: kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: kafka-deployment
      id: "0"
  template:
    metadata:
      labels:
        component: kafka-deployment
        id: "0"
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:6.1.1
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: "load-balancer URL"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zoo1:2181
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_JMX_PORT
              value: "9999"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-service:9092"
#              TODO: Is it necessary a volume?
#          volumeMounts:
#            - name: kafka-volume
#              mountPath: /data/kafka



