apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: monolith-deployment # name of component
  name: monolith-deployment # name of component
spec:  # specifications of the deployment
  replicas: 3  #how many pods I want
  selector:  # how to select the deployment component
    matchLabels:
      component: monolith-deployment  # name of component
  strategy: # strategy of deployment for some changes
    rollingUpdate:  #the method to avoid downtimes
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:  # pods inside the deployment
    metadata:
      labels:
        component: monolith-deployment
    spec:
      containers:
        - name: monolith-container
          env:
            - name: SPRING_DATASOURCE_URL
              value: 'jdbc:mariadb://mariadb-service.default.svc.cluster.local:3306/shrtdb'
          image: hacheev/monolith_systems_monolith:latest
#          livenessProbe: # prove of the server is alife
#            failureThreshold: 3
#            initialDelaySeconds: 20
#            periodSeconds: 20
#            successThreshold: 1
#            tcpSocket:
#              port: 8080
#            timeoutSeconds: 5
          ports:
            - containerPort: 8080
              protocol: TCP
#              name: 8080tcp
#              protocol: TCP
#          readinessProbe:
#            failureThreshold: 14
#            initialDelaySeconds: 40
#            periodSeconds: 10
#            successThreshold: 1
#            tcpSocket:
#              port: 8080
#            timeoutSeconds: 5
          resources:
            limits:
              memory: 500Mi
            requests:
              cpu: 200m
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30