name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:monolith"
          push: true
          tags: hacheev/monolith_systems_monolith:latest, hacheev/monolith_systems_monolith:${{ github.sha }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:events_consumer_service"
          push: true
          tags: hacheev/events-consumer-service:latest, hacheev/events-consumer-service:${{ github.sha }}

